
# Use root/example as user/password credentials
version: '3.1'

services:

  # db:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: qwerty
  #     MYSQL_DATABASE: newsfeed
  #   ports:
  #     - "33066:3306"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: python_news_db
    ports:
      - "54322:5432"
